"""
Download Service — Generate downloadable summary files (PDF and TXT).
Uses fpdf2 for PDF generation.
"""

from fpdf import FPDF
from io import BytesIO


def generate_summary_pdf(
    summary: str,
    original_word_count: int,
    summary_word_count: int,
    filename: str = "summary",
) -> bytes:
    """
    Generate a styled PDF document containing the summary.
    Returns raw PDF bytes.
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Title ──
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(30, 30, 80)
    pdf.cell(0, 15, "PDF Summary Report", ln=True, align="C")
    pdf.ln(5)

    # ── Divider line ──
    pdf.set_draw_color(100, 100, 200)
    pdf.set_line_width(0.5)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(8)

    # ── Stats ──
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Original: {original_word_count} words  |  "
                    f"Summary: {summary_word_count} words  |  "
                    f"Compression: {round((1 - summary_word_count / max(original_word_count, 1)) * 100, 1)}%",
             ln=True, align="C")
    pdf.ln(8)

    # ── Summary body ──
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(30, 30, 30)

    # Handle encoding — replace unsupported characters
    safe_summary = summary.encode("latin-1", errors="replace").decode("latin-1")
    pdf.multi_cell(0, 7, safe_summary)

    pdf.ln(10)

    # ── Footer note ──
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 6, "Generated by PDF Summarizer - powered by BART NLP", ln=True, align="C")

    return bytes(pdf.output())


def generate_summary_txt(
    summary: str,
    original_word_count: int,
    summary_word_count: int,
) -> str:
    """Generate a plain-text summary report."""
    compression = round(
        (1 - summary_word_count / max(original_word_count, 1)) * 100, 1
    )

    return (
        "=" * 60 + "\n"
        "  PDF SUMMARY REPORT\n"
        "=" * 60 + "\n\n"
        f"Original word count:  {original_word_count}\n"
        f"Summary word count:   {summary_word_count}\n"
        f"Compression ratio:    {compression}%\n\n"
        "-" * 60 + "\n"
        "  SUMMARY\n"
        "-" * 60 + "\n\n"
        f"{summary}\n\n"
        "-" * 60 + "\n"
        "Generated by PDF Summarizer - powered by BART NLP\n"
    )

def generate_original_pdf(
    original_text: str,
    original_word_count: int,
) -> bytes:
    """
    Generate a styled PDF document containing the full, nicely formatted original text.
    Returns raw PDF bytes.
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Title ──
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(30, 30, 80)
    pdf.cell(0, 15, "Original Case Document", ln=True, align="C")
    pdf.ln(5)

    # ── Divider line ──
    pdf.set_draw_color(100, 100, 200)
    pdf.set_line_width(0.5)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(8)

    # ── Stats ──
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Word count: {original_word_count} words", ln=True, align="C")
    pdf.ln(8)

    # ── Document body ──
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(30, 30, 30)

    # Clean text: replace multiple newlines with single ones, replace unsupported chars
    import re
    cleaned_text = re.sub(r'\n{3,}', '\n\n', original_text)
    safe_text = cleaned_text.encode("latin-1", errors="replace").decode("latin-1")
    
    pdf.multi_cell(0, 7, safe_text)

    pdf.ln(10)

    # ── Footer note ──
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 6, "Exported from Zilla Parishad Summarizer", ln=True, align="C")

    return bytes(pdf.output())
